# https://github.com/char-lie/mfm
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - sh ./scripts/install-conda.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
install:
  - sudo apt-get install -y python-opengl
  - export CONDA_PACKAGES="numpy scipy"
  - conda create --yes -n testenv python=$TRAVIS_PYTHON_VERSION $CONDA_PACKAGES
  - source activate testenv
script:
  - python setup.py test
after_success:
  - pip install coveralls codeclimate-test-reporter
  - codeclimate-test-reporter
  - coveralls
addons:
  code_climate:
    repo_token: ad7b1d4b1d13f5d5c66dc81580c6f18502dc6c3568d757c1c3ad02e249677989
